#!/usr/bin/env bash
# Deploy the website from the git clone on the server. No git files are copied.
#
# Normally this runs by itself: the git hook hooks/post-merge calls it after
# every "git pull" on the server (see INSTALL.md). To run it by hand:
#     bash ~/rtg_create_labels/deploy.sh [WEB_FOLDER] [--no-pull]
# WEB_FOLDER defaults to the git setting rgt.webdir, e.g.
#     git config rgt.webdir "$HOME/marcellolussana.net/httpdocs/rgt"
#
# What it does:
#   1. git pull (fast-forward only) in the clone, unless --no-pull
#   2. copies the tracked files of public/ to WEB_FOLDER (git archive: no .git,
#      README, tests or scripts)
#   3. writes WEB_FOLDER/private_path.php, which tells api.php to use the
#      private/ folder of this clone (configuration, database access, PHP code)
#   4. runs private/setup.php (checks the configuration and the database
#      connection, creates missing tables)
#
# The clone must be outside the web folder: its private/ folder is used directly
# and must not be reachable from the internet.
#
# Server-only files live in the clone's private/ folder and are ignored by git,
# so git pull never touches them: db_credentials.ini, interviewer_token.hash,
# headphone_manifest.csv, dumps/. Do not run "git clean -x" in the clone: it
# would delete them.
# In WEB_FOLDER, uploaded files (audio, models/, static/vendor/) are not touched.
# Files deleted from the repository are not deleted from WEB_FOLDER.

set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WEB=""
PULL=1
for arg in "$@"; do
  case "$arg" in
    --no-pull) PULL=0 ;;
    *) WEB="$arg" ;;
  esac
done
if [[ -z "$WEB" ]]; then
  WEB="$(git -C "$REPO" config --get rgt.webdir || true)"
fi
if [[ -z "$WEB" ]]; then
  echo "usage: $0 [WEB_FOLDER] [--no-pull]" >&2
  echo "or set the default once:  git -C $REPO config rgt.webdir \"\$HOME/marcellolussana.net/httpdocs/rgt\"" >&2
  exit 1
fi
mkdir -p "$WEB"
WEB="$(cd "$WEB" && pwd -P)"
REPO="$(cd "$REPO" && pwd -P)"

inside() { case "$1/" in "$2/"*) return 0;; esac; return 1; }

# relative path from directory $1 to path $2 (both absolute, normalised);
# plain bash, because "realpath --relative-to" is not available everywhere
relpath() {
  local from="$1" to="$2" up=""
  while [[ -n "$from" && "$to" != "$from" && "$to" != "$from"/* ]]; do
    from="${from%/*}"
    up="../$up"
  done
  if [[ -z "$from" ]]; then
    printf '%s' "${up}${to#/}"
  elif [[ "$to" == "$from" ]]; then
    printf '%s' "${up%/}"
  else
    printf '%s' "${up}${to#"$from"/}"
  fi
}
if inside "$WEB" "$REPO"; then
  echo "error: the web folder must be outside the repository" >&2; exit 1
fi
if inside "$REPO" "$WEB"; then
  echo "error: the repository must not be inside the web folder (private/ and .git would be public)" >&2; exit 1
fi

if [[ "$PULL" == 1 ]]; then
  # hooks disabled here, so the post-merge hook does not deploy a second time
  git -C "$REPO" -c core.hooksPath=/dev/null pull --ff-only
fi
chmod 700 "$REPO/private"

COMMIT="$(git -C "$REPO" rev-parse --short HEAD)"
git -C "$REPO" archive --format=tar HEAD:public | tar -x -C "$WEB"

# tell api.php where the private folder is (generated, not in git).
# The path is written RELATIVE to the web folder: on shared hosting, the SSH
# session and the web server's PHP may see the webspace under different
# absolute paths (on netcup, SSH sees the webspace as "/").
PRIV="$REPO/private"
REL="$(relpath "$WEB" "$PRIV")"
if [[ -n "$REL" ]]; then
  printf "<?php\n// Generated by deploy.sh. Path of the private folder, relative to this file.\nreturn __DIR__ . '/%s';\n" \
    "${REL//\'/\\\'}" > "$WEB/private_path.php"
else
  printf "<?php\n// Generated by deploy.sh. Path of the private folder.\nreturn '%s';\n" \
    "${PRIV//\'/\\\'}" > "$WEB/private_path.php"
fi

echo "deployed commit $COMMIT"
echo "  web folder:     $WEB"
echo "  private folder: $PRIV"

php "$PRIV/setup.php" --public-dir "$WEB"
