#!/usr/bin/env bash
# Deploy from the git clone on the server. No git files are copied.
#
# Usage on the server (via SSH):
#     bash ~/rtg_create_labels/deploy.sh WEB_FOLDER PRIVATE_FOLDER [--no-pull]
# for example
#     bash ~/rtg_create_labels/deploy.sh ~/httpdocs/rgt ~/rgt_private
#
# What it does:
#   1. git pull (fast-forward only) in the clone, unless --no-pull
#   2. copies the tracked files of public/  to WEB_FOLDER      (reachable from the internet)
#      copies the tracked files of private/ to PRIVATE_FOLDER  (NOT reachable from the internet)
#      using git archive, so no .git folder, README, tests or scripts are copied
#   3. writes WEB_FOLDER/private_path.php, which tells api.php where the private folder is
#   4. runs PRIVATE_FOLDER/setup.php (checks the configuration and the database
#      connection, creates missing tables)
#
# Files that exist only on the server are never touched, because they are not in git:
#   PRIVATE_FOLDER: db_credentials.ini, interviewer_token.hash, headphone_manifest.csv, dumps/
#   WEB_FOLDER:     audio files, models/, static/vendor/
# Tracked files ARE overwritten, including private/config.ini: change the
# configuration in the repository, commit, push, and deploy again.
# Files deleted from the repository are not deleted on the server.

set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WEB="${1:-}"
PRIV="${2:-}"
if [[ -z "$WEB" || -z "$PRIV" || "$PRIV" == --* ]]; then
  echo "usage: $0 WEB_FOLDER PRIVATE_FOLDER [--no-pull]" >&2
  echo "example: $0 ~/httpdocs/rgt ~/rgt_private" >&2
  exit 1
fi
mkdir -p "$WEB" "$PRIV"
WEB="$(cd "$WEB" && pwd)"
PRIV="$(cd "$PRIV" && pwd)"
chmod 700 "$PRIV"

inside() { case "$1/" in "$2/"*) return 0;; esac; return 1; }
if inside "$WEB" "$REPO" || inside "$PRIV" "$REPO"; then
  echo "error: web and private folders must be outside the repository" >&2; exit 1
fi
if inside "$REPO" "$WEB"; then
  echo "error: the repository must not be inside the web folder (the .git folder would be public)" >&2; exit 1
fi
if inside "$PRIV" "$WEB"; then
  echo "error: the private folder must not be inside the web folder" >&2; exit 1
fi

if [[ "${3:-}" != "--no-pull" ]]; then
  git -C "$REPO" pull --ff-only
fi

COMMIT="$(git -C "$REPO" rev-parse --short HEAD)"
git -C "$REPO" archive --format=tar HEAD:public  | tar -x -C "$WEB"
git -C "$REPO" archive --format=tar HEAD:private | tar -x -C "$PRIV"

# tell api.php where the private folder is (generated, not in git)
printf "<?php\n// Generated by deploy.sh. Path of the private folder (outside the web folder).\nreturn '%s';\n" \
  "${PRIV//\'/\\\'}" > "$WEB/private_path.php"

echo "deployed commit $COMMIT"
echo "  web folder:     $WEB"
echo "  private folder: $PRIV"

php "$PRIV/setup.php" --public-dir "$WEB"
